---
# Common config variables
common:
    paths:
        source_path_wd : 'E:/U-CAN-Lymfom_A' #'/media/andres/T7 Shield1/U-CAN-Lymfom_A'
        source_path_bd : '/media/andres/T7 Shield/ucan_lymfom' #'F:/ucan_lymfom'

# Selection script config variables
selection:
    filenames:
        rejected_folder_filename : 'Rejected_exams_from_U-CAN-Lymfom.xlsx'
        sourcefiltered_folder_filename : 'SourceFiltered_exams_from_U-CAN-Lymfom.xlsx'
        incomplete_folders_filename_initial : 'No_PTorCT_exams_from_U-CAN-Lymfom1.xlsx'
        incomplete_folders_filename_final : 'No_PTorCT_exams_from_U-CAN-Lymfom2.xlsx'
        selected_folders_beforefiltering_filename : 'Selected_exams_beforefiltering_from_U-CAN-Lymfom.xlsx'
        selected_folders_afterfiltering_filename : 'Selected_exams_afterfiltering_from_U-CAN-Lymfom.xlsx'
        final_selected_images_filename : 'Excel_files/06_11_2023/Final_Selected_exams_from_U-CAN-Lymfom.xlsx'
        list_of_distorted_images_filename : 'Distorted_exams_from_U-CAN-Lymfom.xlsx'

# Metadata extraction config variables
metadata:
    filenames:
        final_selected_images_filename : 'Finalized_dataset.xlsx'


# Resampling Task config variables
resampling:
    voxel_spacing : [2.0364201068878174, 2.0364201068878174, 3.0]
    image_size : [256,256,256]

# Projection config variables
projections:
    paths:
        destination_path : 'Selected_for_UCAN_project/2dprojections' 
    variables:
        modality : ['CT', 'PT', 'SUV']
        tissue_type : ['LT', 'AT', 'LT' , 'B' , 'N']
        projection_type : ['sum', 'min', 'max', 'mean', 'std']
        angles : [0, 90]
...